### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by c0d3x27** [angry-bender/SUOPE#2]
hi 

first of all thank you for making this. also I want to point out that is not working for me 
`AttributeError: type object 'AuthHandler' has no attribute 'client_client_handler_table'`

what am I doing wrong ?

**Comment by angry-bender** [comment]
Sounds like an error in the cryptography library. What's the full
input/output

**Comment by c0d3x27** [comment]
fixed already thank you again

**Comment by angry-bender** [comment]
No worries, Good code courtesy is to let people know how to fix it in case
they have the same issue, or, so a coder can fix it 🙂

If you wouldn't mind letting us know that would be awesome.
